// <auto-generated />
using System;
using GreenHouse.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreenHouse.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251108141044_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GreenHouse.Models.Plant", b =>
                {
                    b.Property<string>("PlantName")
                        .HasColumnType("char(30)")
                        .HasColumnName("PLANT_NAME");

                    b.Property<DateTime>("SensorEvent")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("SENSOR_EVENT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<float>("SensorValue")
                        .HasColumnType("real")
                        .HasColumnName("SENSOR_VALUE");

                    b.HasKey("PlantName")
                        .HasName("PK_PLANTS");

                    b.ToTable("PLANTS");
                });
#pragma warning restore 612, 618
        }
    }
}
